
spring:
  data:
    mongodb:
      uri: mongodb://root:example@127.0.0.1:27017
      database: products
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey
