version: '3.0'

services:

  mongodb:
    container_name: chaos-monkey-mongodb
    image: mongo:4.2.3
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: chaos

volumes:
  mongodb-volume:
